# Generated by Django 5.1.4 on 2025-01-21 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='customer', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('image', models.ImageField(default='images/default/default_customer.png', upload_to='images/default/')),
                ('full_address', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='seller', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.ImageField(default='images/default/default_seller.png', upload_to='images/default/')),
                ('mobile_no', models.CharField(max_length=16)),
                ('full_address', models.CharField(max_length=250)),
            ],
        ),
    ]
