# Generated by Django 5.1.4 on 2025-01-21 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_initial'),
        ('shop', '0004_shop_total_sold'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mango',
            new_name='Product',
        ),
    ]
