# Generated by Django 5.1.4 on 2025-01-18 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mango',
            old_name='categories',
            new_name='category',
        ),
    ]
