# Generated by Django 5.1.4 on 2025-01-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(default='images/default/default_mango.png', upload_to='images/shops/')),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=250)),
                ('hotline', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('rank', models.IntegerField(default=0)),
            ],
        ),
    ]
