# Generated by Django 5.1.4 on 2025-01-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='hotline',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
