# Generated by Django 5.1.4 on 2025-01-21 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='rank',
        ),
    ]
