# Generated by Django 5.1.4 on 2025-01-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shop_hotline'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='total_sold',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
